version: '3.1'

networks:
  ghost:

services:
  ghost-app:
    image: ghost:4-alpine
    container_name: ghost
    networks:
      - ghost
    depends_on:
      - db
    ports:
      - 2368:2368

  nginx:
    image: nginx:1.20.1-alpine
    restart: always
    container_name: nginx
    networks:
      - ghost
    depends_on:
      - ghost-app
    ports:
      - 80:80

  db:
    image: mysql:5.7.15
    container_name: mysql
    restart: always
    networks:
      - ghost
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ghost
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: ghost
    volumes:
      - $PWD/db:/var/lib/mysql
    ports:
      - 8080:3306