version: '3.1'

networks:
  public_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
      driver: default

services:

  apache_1:
    image: httpd:2.4
    container_name: apache_1
    expose:
      - 80
    networks:
      public_net:
        ipv4_address: 192.168.0.11

  apache_2:
    image: httpd:2.4
    container_name: apache_2
    expose:
      - 80
    networks:
      public_net:
        ipv4_address: 192.168.0.12

  haproxy:
    image: haproxy:1.7
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    environment:
      APACHE_1_IP: 192.168.0.11
      APACHE_2_IP: 192.168.0.12
      APACHE_EXPOSED_PORT: 80
    expose:
      - 80
    networks:
      public_net:
        ipv4_address: 192.168.0.13
    ports:
      - 80:80/tcp
